// <auto-generated />
using System;
using GestionBudget.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DentisteApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241110015927_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DentisteApp.Models.Entities.Acte", b =>
                {
                    b.Property<int>("ActeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActeID"));

                    b.Property<DateTime>("DateActe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DossierMedicalID")
                        .HasColumnType("integer");

                    b.Property<string>("TypeActe")
                        .HasColumnType("text");

                    b.HasKey("ActeID");

                    b.HasIndex("DossierMedicalID");

                    b.ToTable("Acte");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.CertificatMedical", b =>
                {
                    b.Property<int>("CertificatMedicalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CertificatMedicalID"));

                    b.Property<DateTime>("DateCertificat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DossierMedicalID")
                        .HasColumnType("integer");

                    b.Property<int>("Duree")
                        .HasColumnType("integer");

                    b.Property<string>("Raison")
                        .HasColumnType("text");

                    b.HasKey("CertificatMedicalID");

                    b.HasIndex("DossierMedicalID");

                    b.ToTable("CertificatsMedicaux");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.DossierMedical", b =>
                {
                    b.Property<int>("DossierMedicalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DossierMedicalID"));

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.HasKey("DossierMedicalID");

                    b.HasIndex("PatientID");

                    b.ToTable("DossiersMedicaux");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.Facture", b =>
                {
                    b.Property<int>("FactureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FactureID"));

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DossierMedicalID")
                        .HasColumnType("integer");

                    b.Property<string>("EtatPaiement")
                        .HasColumnType("text");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("numeric");

                    b.HasKey("FactureID");

                    b.HasIndex("DossierMedicalID");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.FeuilleDeSoin", b =>
                {
                    b.Property<int>("FeuilleDeSoinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeuilleDeSoinID"));

                    b.Property<DateTime>("DateFeuille")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DossierMedicalID")
                        .HasColumnType("integer");

                    b.HasKey("FeuilleDeSoinID");

                    b.HasIndex("DossierMedicalID");

                    b.ToTable("FeuillesDeSoin");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.Imagerie", b =>
                {
                    b.Property<int>("ImagerieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImagerieID"));

                    b.Property<DateTime>("DateImagerie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DossierMedicalID")
                        .HasColumnType("integer");

                    b.Property<string>("TypeImagerie")
                        .HasColumnType("text");

                    b.Property<string>("UrlImage")
                        .HasColumnType("text");

                    b.HasKey("ImagerieID");

                    b.HasIndex("DossierMedicalID");

                    b.ToTable("Imageries");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.Ordonnance", b =>
                {
                    b.Property<int>("OrdonnanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdonnanceID"));

                    b.Property<DateTime>("DateOrdonnance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DossierMedicalID")
                        .HasColumnType("integer");

                    b.Property<string>("Medicaments")
                        .HasColumnType("text");

                    b.HasKey("OrdonnanceID");

                    b.HasIndex("DossierMedicalID");

                    b.ToTable("Ordonnances");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.Paiement", b =>
                {
                    b.Property<int>("PaiementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaiementID"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DossierMedicalID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric");

                    b.Property<string>("MoyenPaiement")
                        .HasColumnType("text");

                    b.HasKey("PaiementID");

                    b.HasIndex("DossierMedicalID");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.HasKey("PatientID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.Acte", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.DossierMedical", null)
                        .WithMany("Actes")
                        .HasForeignKey("DossierMedicalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.CertificatMedical", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.DossierMedical", null)
                        .WithMany("CertificatsMedicaux")
                        .HasForeignKey("DossierMedicalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.DossierMedical", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.Facture", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.DossierMedical", null)
                        .WithMany("Factures")
                        .HasForeignKey("DossierMedicalID");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.FeuilleDeSoin", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.DossierMedical", null)
                        .WithMany("FeuillesDeSoin")
                        .HasForeignKey("DossierMedicalID");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.Imagerie", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.DossierMedical", null)
                        .WithMany("Imageries")
                        .HasForeignKey("DossierMedicalID");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.Ordonnance", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.DossierMedical", null)
                        .WithMany("Ordonnances")
                        .HasForeignKey("DossierMedicalID");
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.Paiement", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.DossierMedical", null)
                        .WithMany("Paiements")
                        .HasForeignKey("DossierMedicalID");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentisteApp.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DentisteApp.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DentisteApp.Models.Entities.DossierMedical", b =>
                {
                    b.Navigation("Actes");

                    b.Navigation("CertificatsMedicaux");

                    b.Navigation("Factures");

                    b.Navigation("FeuillesDeSoin");

                    b.Navigation("Imageries");

                    b.Navigation("Ordonnances");

                    b.Navigation("Paiements");
                });
#pragma warning restore 612, 618
        }
    }
}
